# Generated by Django 3.1.3 on 2020-11-09 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('placeName', models.CharField(default=False, max_length=40)),
                ('kakaoId', models.CharField(default=False, max_length=40, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=200)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('body', models.TextField()),
                ('regUserId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='login.user')),
            ],
            options={
                'verbose_name': 'place info table',
                'db_table': 'place',
            },
        ),
    ]
