# Generated by Django 3.1.3 on 2020-11-10 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.FloatField()),
                ('body', models.TextField()),
                ('kakaoId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='place.place')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='login.user')),
            ],
            options={
                'verbose_name': 'place review table',
                'db_table': 'review',
            },
        ),
    ]
