# Generated by Django 3.1.3 on 2020-11-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(default=False, max_length=30)),
                ('userEmail', models.CharField(default=False, max_length=30, unique=True)),
                ('pw', models.CharField(default=False, max_length=256)),
                ('gender', models.IntegerField()),
                ('birth', models.CharField(max_length=20)),
                ('userType', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'user info table',
                'db_table': 'user',
            },
        ),
    ]
